[package]
name = "scoplen-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Scoplen encrypted synchronization service."

[dependencies]
axum.workspace = true
scoplen-api = { git = "https://github.com/plystra/scoplen-proto.git", rev = "9dcaebd" }
scoplen-model = { git = "https://github.com/plystra/scoplen-proto.git", rev = "9dcaebd" }
scoplen-store = { path = "../scoplen-store" }
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
tower = "0.5.2"

[lints]
workspace = true
