[package]
name = "scoplen-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Scoplen encrypted synchronization service."

[dependencies]
axum.workspace = true
scoplen-api = { git = "https://github.com/plystra/scoplen-proto.git", rev = "cc549fd" }
scoplen-model = { git = "https://github.com/plystra/scoplen-proto.git", rev = "cc549fd" }
scoplen-store = { path = "../scoplen-store" }
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
futures-util = "0.3.34"
tokio-tungstenite = "0.26.2"
tower = "0.5.2"

[lints]
workspace = true
