[package]
name = "scoplen-store"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Scoplen storage abstraction."

[lints]
workspace = true

[dependencies]
bytes.workspace = true
futures-util.workspace = true
object_store.workspace = true
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "sqlite", "postgres", "migrate", "macros"] }
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
uuid.workspace = true

[features]
postgres-integration = []
